# Generated by Django 3.1.2 on 2020-10-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
