# Generated by Django 3.1.2 on 2020-10-04 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_apps', '0005_auto_20201004_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='question',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='test',
            name='date_added',
        ),
    ]
