# Generated by Django 3.1.2 on 2020-10-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_apps', '0008_auto_20201004_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res', models.IntegerField(default=0)),
                ('ind', models.IntegerField(default=0)),
            ],
        ),
    ]
